geelasticsearch:
  container_name: elk_elasticsearch
  image: elasticsearch:latest
  ports:
    - "9200:9200"

kibana:
  container_name: elk_kibana
  image: kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch

logstash:
  container_name: elk_logstash
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  image: logstash:latest
  volumes:
    - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
  expose:
    - "12201"
  ports:
    - "5000:5000"
    - "12201:12201"
    - "12201:12201/udp"
  links:
    - elasticsearch
